"use strict";
/* tslint:disable */
Object.defineProperty(exports, "__esModule", { value: true });
/**
 * This file has been automatically generated by the [capnpc-ts utility](https://github.com/jdiaz5513/capnp-ts).
 */
const capnp = require("capnp-ts");
const capnp_ts_1 = require("capnp-ts");
exports._capnpFileId = "8e2af1e708af8b8d";
var CarEvent_EventName;
(function (CarEvent_EventName) {
    CarEvent_EventName[CarEvent_EventName["CAN_ERROR"] = 0] = "CAN_ERROR";
    CarEvent_EventName[CarEvent_EventName["STEER_UNAVAILABLE"] = 1] = "STEER_UNAVAILABLE";
    CarEvent_EventName[CarEvent_EventName["BRAKE_UNAVAILABLE"] = 2] = "BRAKE_UNAVAILABLE";
    CarEvent_EventName[CarEvent_EventName["WRONG_GEAR"] = 3] = "WRONG_GEAR";
    CarEvent_EventName[CarEvent_EventName["DOOR_OPEN"] = 4] = "DOOR_OPEN";
    CarEvent_EventName[CarEvent_EventName["SEATBELT_NOT_LATCHED"] = 5] = "SEATBELT_NOT_LATCHED";
    CarEvent_EventName[CarEvent_EventName["ESP_DISABLED"] = 6] = "ESP_DISABLED";
    CarEvent_EventName[CarEvent_EventName["WRONG_CAR_MODE"] = 7] = "WRONG_CAR_MODE";
    CarEvent_EventName[CarEvent_EventName["STEER_TEMP_UNAVAILABLE"] = 8] = "STEER_TEMP_UNAVAILABLE";
    CarEvent_EventName[CarEvent_EventName["REVERSE_GEAR"] = 9] = "REVERSE_GEAR";
    CarEvent_EventName[CarEvent_EventName["BUTTON_CANCEL"] = 10] = "BUTTON_CANCEL";
    CarEvent_EventName[CarEvent_EventName["BUTTON_ENABLE"] = 11] = "BUTTON_ENABLE";
    CarEvent_EventName[CarEvent_EventName["PEDAL_PRESSED"] = 12] = "PEDAL_PRESSED";
    CarEvent_EventName[CarEvent_EventName["CRUISE_DISABLED"] = 13] = "CRUISE_DISABLED";
    CarEvent_EventName[CarEvent_EventName["SPEED_TOO_LOW"] = 14] = "SPEED_TOO_LOW";
    CarEvent_EventName[CarEvent_EventName["OUT_OF_SPACE"] = 15] = "OUT_OF_SPACE";
    CarEvent_EventName[CarEvent_EventName["OVERHEAT"] = 16] = "OVERHEAT";
    CarEvent_EventName[CarEvent_EventName["CALIBRATION_INCOMPLETE"] = 17] = "CALIBRATION_INCOMPLETE";
    CarEvent_EventName[CarEvent_EventName["CALIBRATION_INVALID"] = 18] = "CALIBRATION_INVALID";
    CarEvent_EventName[CarEvent_EventName["CONTROLS_MISMATCH"] = 19] = "CONTROLS_MISMATCH";
    CarEvent_EventName[CarEvent_EventName["PCM_ENABLE"] = 20] = "PCM_ENABLE";
    CarEvent_EventName[CarEvent_EventName["PCM_DISABLE"] = 21] = "PCM_DISABLE";
    CarEvent_EventName[CarEvent_EventName["NO_TARGET"] = 22] = "NO_TARGET";
    CarEvent_EventName[CarEvent_EventName["RADAR_FAULT"] = 23] = "RADAR_FAULT";
    CarEvent_EventName[CarEvent_EventName["BRAKE_HOLD"] = 24] = "BRAKE_HOLD";
    CarEvent_EventName[CarEvent_EventName["PARK_BRAKE"] = 25] = "PARK_BRAKE";
    CarEvent_EventName[CarEvent_EventName["MANUAL_RESTART"] = 26] = "MANUAL_RESTART";
    CarEvent_EventName[CarEvent_EventName["LOW_SPEED_LOCKOUT"] = 27] = "LOW_SPEED_LOCKOUT";
    CarEvent_EventName[CarEvent_EventName["PLANNER_ERROR"] = 28] = "PLANNER_ERROR";
    CarEvent_EventName[CarEvent_EventName["DEBUG_ALERT"] = 29] = "DEBUG_ALERT";
    CarEvent_EventName[CarEvent_EventName["STEER_TEMP_UNAVAILABLE_USER_OVERRIDE"] = 30] = "STEER_TEMP_UNAVAILABLE_USER_OVERRIDE";
    CarEvent_EventName[CarEvent_EventName["RESUME_REQUIRED"] = 31] = "RESUME_REQUIRED";
    CarEvent_EventName[CarEvent_EventName["PRE_DRIVER_DISTRACTED"] = 32] = "PRE_DRIVER_DISTRACTED";
    CarEvent_EventName[CarEvent_EventName["PROMPT_DRIVER_DISTRACTED"] = 33] = "PROMPT_DRIVER_DISTRACTED";
    CarEvent_EventName[CarEvent_EventName["DRIVER_DISTRACTED"] = 34] = "DRIVER_DISTRACTED";
    CarEvent_EventName[CarEvent_EventName["PRE_DRIVER_UNRESPONSIVE"] = 35] = "PRE_DRIVER_UNRESPONSIVE";
    CarEvent_EventName[CarEvent_EventName["PROMPT_DRIVER_UNRESPONSIVE"] = 36] = "PROMPT_DRIVER_UNRESPONSIVE";
    CarEvent_EventName[CarEvent_EventName["DRIVER_UNRESPONSIVE"] = 37] = "DRIVER_UNRESPONSIVE";
    CarEvent_EventName[CarEvent_EventName["BELOW_STEER_SPEED"] = 38] = "BELOW_STEER_SPEED";
    CarEvent_EventName[CarEvent_EventName["LOW_BATTERY"] = 39] = "LOW_BATTERY";
    CarEvent_EventName[CarEvent_EventName["VEHICLE_MODEL_INVALID"] = 40] = "VEHICLE_MODEL_INVALID";
    CarEvent_EventName[CarEvent_EventName["ACC_FAULTED"] = 41] = "ACC_FAULTED";
    CarEvent_EventName[CarEvent_EventName["SENSOR_DATA_INVALID"] = 42] = "SENSOR_DATA_INVALID";
    CarEvent_EventName[CarEvent_EventName["COMM_ISSUE"] = 43] = "COMM_ISSUE";
    CarEvent_EventName[CarEvent_EventName["TOO_DISTRACTED"] = 44] = "TOO_DISTRACTED";
    CarEvent_EventName[CarEvent_EventName["POSENET_INVALID"] = 45] = "POSENET_INVALID";
    CarEvent_EventName[CarEvent_EventName["SOUNDS_UNAVAILABLE"] = 46] = "SOUNDS_UNAVAILABLE";
    CarEvent_EventName[CarEvent_EventName["PRE_LANE_CHANGE_LEFT"] = 47] = "PRE_LANE_CHANGE_LEFT";
    CarEvent_EventName[CarEvent_EventName["PRE_LANE_CHANGE_RIGHT"] = 48] = "PRE_LANE_CHANGE_RIGHT";
    CarEvent_EventName[CarEvent_EventName["LANE_CHANGE"] = 49] = "LANE_CHANGE";
    CarEvent_EventName[CarEvent_EventName["COMMUNITY_FEATURE_DISALLOWED"] = 50] = "COMMUNITY_FEATURE_DISALLOWED";
    CarEvent_EventName[CarEvent_EventName["LOW_MEMORY"] = 51] = "LOW_MEMORY";
    CarEvent_EventName[CarEvent_EventName["STOCK_AEB"] = 52] = "STOCK_AEB";
    CarEvent_EventName[CarEvent_EventName["LDW"] = 53] = "LDW";
    CarEvent_EventName[CarEvent_EventName["CAR_UNRECOGNIZED"] = 54] = "CAR_UNRECOGNIZED";
    CarEvent_EventName[CarEvent_EventName["DRIVER_MONITOR_LOW_ACC"] = 55] = "DRIVER_MONITOR_LOW_ACC";
    CarEvent_EventName[CarEvent_EventName["INVALID_LKAS_SETTING"] = 56] = "INVALID_LKAS_SETTING";
    CarEvent_EventName[CarEvent_EventName["SPEED_TOO_HIGH"] = 57] = "SPEED_TOO_HIGH";
    CarEvent_EventName[CarEvent_EventName["LANE_CHANGE_BLOCKED"] = 58] = "LANE_CHANGE_BLOCKED";
    CarEvent_EventName[CarEvent_EventName["RELAY_MALFUNCTION"] = 59] = "RELAY_MALFUNCTION";
    CarEvent_EventName[CarEvent_EventName["GAS_PRESSED"] = 60] = "GAS_PRESSED";
    CarEvent_EventName[CarEvent_EventName["STOCK_FCW"] = 61] = "STOCK_FCW";
    CarEvent_EventName[CarEvent_EventName["STARTUP"] = 62] = "STARTUP";
    CarEvent_EventName[CarEvent_EventName["STARTUP_NO_CAR"] = 63] = "STARTUP_NO_CAR";
    CarEvent_EventName[CarEvent_EventName["STARTUP_NO_CONTROL"] = 64] = "STARTUP_NO_CONTROL";
    CarEvent_EventName[CarEvent_EventName["STARTUP_MASTER"] = 65] = "STARTUP_MASTER";
    CarEvent_EventName[CarEvent_EventName["STARTUP_FUZZY_FINGERPRINT"] = 66] = "STARTUP_FUZZY_FINGERPRINT";
    CarEvent_EventName[CarEvent_EventName["FCW"] = 67] = "FCW";
    CarEvent_EventName[CarEvent_EventName["STEER_SATURATED"] = 68] = "STEER_SATURATED";
    CarEvent_EventName[CarEvent_EventName["BELOW_ENGAGE_SPEED"] = 69] = "BELOW_ENGAGE_SPEED";
    CarEvent_EventName[CarEvent_EventName["NO_GPS"] = 70] = "NO_GPS";
    CarEvent_EventName[CarEvent_EventName["WRONG_CRUISE_MODE"] = 71] = "WRONG_CRUISE_MODE";
    CarEvent_EventName[CarEvent_EventName["MODELD_LAGGING"] = 72] = "MODELD_LAGGING";
    CarEvent_EventName[CarEvent_EventName["DEVICE_FALLING"] = 73] = "DEVICE_FALLING";
    CarEvent_EventName[CarEvent_EventName["FAN_MALFUNCTION"] = 74] = "FAN_MALFUNCTION";
    CarEvent_EventName[CarEvent_EventName["CAMERA_MALFUNCTION"] = 75] = "CAMERA_MALFUNCTION";
    CarEvent_EventName[CarEvent_EventName["GPS_MALFUNCTION"] = 76] = "GPS_MALFUNCTION";
    CarEvent_EventName[CarEvent_EventName["PROCESS_NOT_RUNNING"] = 77] = "PROCESS_NOT_RUNNING";
    CarEvent_EventName[CarEvent_EventName["DASHCAM_MODE"] = 78] = "DASHCAM_MODE";
    CarEvent_EventName[CarEvent_EventName["CONTROLS_INITIALIZING"] = 79] = "CONTROLS_INITIALIZING";
    CarEvent_EventName[CarEvent_EventName["RADAR_CAN_ERROR_DEPRECATED"] = 80] = "RADAR_CAN_ERROR_DEPRECATED";
    CarEvent_EventName[CarEvent_EventName["RADAR_COMM_ISSUE_DEPRECATED"] = 81] = "RADAR_COMM_ISSUE_DEPRECATED";
    CarEvent_EventName[CarEvent_EventName["GAS_UNAVAILABLE_DEPRECATED"] = 82] = "GAS_UNAVAILABLE_DEPRECATED";
    CarEvent_EventName[CarEvent_EventName["DATA_NEEDED_DEPRECATED"] = 83] = "DATA_NEEDED_DEPRECATED";
    CarEvent_EventName[CarEvent_EventName["MODEL_COMM_ISSUE_DEPRECATED"] = 84] = "MODEL_COMM_ISSUE_DEPRECATED";
    CarEvent_EventName[CarEvent_EventName["IPAS_OVERRIDE_DEPRECATED"] = 85] = "IPAS_OVERRIDE_DEPRECATED";
    CarEvent_EventName[CarEvent_EventName["GEOFENCE_DEPRECATED"] = 86] = "GEOFENCE_DEPRECATED";
    CarEvent_EventName[CarEvent_EventName["DRIVER_MONITOR_ON_DEPRECATED"] = 87] = "DRIVER_MONITOR_ON_DEPRECATED";
    CarEvent_EventName[CarEvent_EventName["DRIVER_MONITOR_OFF_DEPRECATED"] = 88] = "DRIVER_MONITOR_OFF_DEPRECATED";
    CarEvent_EventName[CarEvent_EventName["CALIBRATION_PROGRESS_DEPRECATED"] = 89] = "CALIBRATION_PROGRESS_DEPRECATED";
    CarEvent_EventName[CarEvent_EventName["INVALID_GIRAFFE_HONDA_DEPRECATED"] = 90] = "INVALID_GIRAFFE_HONDA_DEPRECATED";
    CarEvent_EventName[CarEvent_EventName["INVALID_GIRAFFE_TOYOTA_DEPRECATED"] = 91] = "INVALID_GIRAFFE_TOYOTA_DEPRECATED";
    CarEvent_EventName[CarEvent_EventName["INTERNET_CONNECTIVITY_NEEDED_DEPRECATED"] = 92] = "INTERNET_CONNECTIVITY_NEEDED_DEPRECATED";
    CarEvent_EventName[CarEvent_EventName["WHITE_PANDA_UNSUPPORTED_DEPRECATED"] = 93] = "WHITE_PANDA_UNSUPPORTED_DEPRECATED";
    CarEvent_EventName[CarEvent_EventName["COMM_ISSUE_WARNING_DEPRECATED"] = 94] = "COMM_ISSUE_WARNING_DEPRECATED";
    CarEvent_EventName[CarEvent_EventName["FOCUS_RECOVER_ACTIVE_DEPRECATED"] = 95] = "FOCUS_RECOVER_ACTIVE_DEPRECATED";
    CarEvent_EventName[CarEvent_EventName["NEOS_UPDATE_REQUIRED_DEPRECATED"] = 96] = "NEOS_UPDATE_REQUIRED_DEPRECATED";
    CarEvent_EventName[CarEvent_EventName["MODEL_LAG_WARNING_DEPRECATED"] = 97] = "MODEL_LAG_WARNING_DEPRECATED";
    CarEvent_EventName[CarEvent_EventName["STARTUP_ONEPLUS_DEPRECATED"] = 98] = "STARTUP_ONEPLUS_DEPRECATED";
})(CarEvent_EventName = exports.CarEvent_EventName || (exports.CarEvent_EventName = {}));
class CarEvent extends capnp_ts_1.Struct {
    getName() { return capnp_ts_1.Struct.getUint16(0, this); }
    setName(value) { capnp_ts_1.Struct.setUint16(0, value, this); }
    getEnable() { return capnp_ts_1.Struct.getBit(16, this); }
    setEnable(value) { capnp_ts_1.Struct.setBit(16, value, this); }
    getNoEntry() { return capnp_ts_1.Struct.getBit(17, this); }
    setNoEntry(value) { capnp_ts_1.Struct.setBit(17, value, this); }
    getWarning() { return capnp_ts_1.Struct.getBit(18, this); }
    setWarning(value) { capnp_ts_1.Struct.setBit(18, value, this); }
    getUserDisable() { return capnp_ts_1.Struct.getBit(19, this); }
    setUserDisable(value) { capnp_ts_1.Struct.setBit(19, value, this); }
    getSoftDisable() { return capnp_ts_1.Struct.getBit(20, this); }
    setSoftDisable(value) { capnp_ts_1.Struct.setBit(20, value, this); }
    getImmediateDisable() { return capnp_ts_1.Struct.getBit(21, this); }
    setImmediateDisable(value) { capnp_ts_1.Struct.setBit(21, value, this); }
    getPreEnable() { return capnp_ts_1.Struct.getBit(22, this); }
    setPreEnable(value) { capnp_ts_1.Struct.setBit(22, value, this); }
    getPermanent() { return capnp_ts_1.Struct.getBit(23, this); }
    setPermanent(value) { capnp_ts_1.Struct.setBit(23, value, this); }
    toString() { return "CarEvent_" + super.toString(); }
}
CarEvent.EventName = CarEvent_EventName;
CarEvent._capnp = { displayName: "CarEvent", id: "9b1657f34caf3ad3", size: new capnp_ts_1.ObjectSize(8, 0) };
exports.CarEvent = CarEvent;
class CarState_WheelSpeeds extends capnp_ts_1.Struct {
    getFl() { return capnp_ts_1.Struct.getFloat32(0, this); }
    setFl(value) { capnp_ts_1.Struct.setFloat32(0, value, this); }
    getFr() { return capnp_ts_1.Struct.getFloat32(4, this); }
    setFr(value) { capnp_ts_1.Struct.setFloat32(4, value, this); }
    getRl() { return capnp_ts_1.Struct.getFloat32(8, this); }
    setRl(value) { capnp_ts_1.Struct.setFloat32(8, value, this); }
    getRr() { return capnp_ts_1.Struct.getFloat32(12, this); }
    setRr(value) { capnp_ts_1.Struct.setFloat32(12, value, this); }
    toString() { return "CarState_WheelSpeeds_" + super.toString(); }
}
CarState_WheelSpeeds._capnp = { displayName: "WheelSpeeds", id: "991a37a6155935a3", size: new capnp_ts_1.ObjectSize(16, 0) };
exports.CarState_WheelSpeeds = CarState_WheelSpeeds;
class CarState_CruiseState extends capnp_ts_1.Struct {
    getEnabled() { return capnp_ts_1.Struct.getBit(0, this); }
    setEnabled(value) { capnp_ts_1.Struct.setBit(0, value, this); }
    getSpeed() { return capnp_ts_1.Struct.getFloat32(4, this); }
    setSpeed(value) { capnp_ts_1.Struct.setFloat32(4, value, this); }
    getAvailable() { return capnp_ts_1.Struct.getBit(1, this); }
    setAvailable(value) { capnp_ts_1.Struct.setBit(1, value, this); }
    getSpeedOffset() { return capnp_ts_1.Struct.getFloat32(8, this); }
    setSpeedOffset(value) { capnp_ts_1.Struct.setFloat32(8, value, this); }
    getStandstill() { return capnp_ts_1.Struct.getBit(2, this); }
    setStandstill(value) { capnp_ts_1.Struct.setBit(2, value, this); }
    getNonAdaptive() { return capnp_ts_1.Struct.getBit(3, this); }
    setNonAdaptive(value) { capnp_ts_1.Struct.setBit(3, value, this); }
    toString() { return "CarState_CruiseState_" + super.toString(); }
}
CarState_CruiseState._capnp = { displayName: "CruiseState", id: "e64e81478e6e60af", size: new capnp_ts_1.ObjectSize(16, 0) };
exports.CarState_CruiseState = CarState_CruiseState;
var CarState_GearShifter;
(function (CarState_GearShifter) {
    CarState_GearShifter[CarState_GearShifter["UNKNOWN"] = 0] = "UNKNOWN";
    CarState_GearShifter[CarState_GearShifter["PARK"] = 1] = "PARK";
    CarState_GearShifter[CarState_GearShifter["DRIVE"] = 2] = "DRIVE";
    CarState_GearShifter[CarState_GearShifter["NEUTRAL"] = 3] = "NEUTRAL";
    CarState_GearShifter[CarState_GearShifter["REVERSE"] = 4] = "REVERSE";
    CarState_GearShifter[CarState_GearShifter["SPORT"] = 5] = "SPORT";
    CarState_GearShifter[CarState_GearShifter["LOW"] = 6] = "LOW";
    CarState_GearShifter[CarState_GearShifter["BRAKE"] = 7] = "BRAKE";
    CarState_GearShifter[CarState_GearShifter["ECO"] = 8] = "ECO";
    CarState_GearShifter[CarState_GearShifter["MANUMATIC"] = 9] = "MANUMATIC";
})(CarState_GearShifter = exports.CarState_GearShifter || (exports.CarState_GearShifter = {}));
var CarState_ButtonEvent_Type;
(function (CarState_ButtonEvent_Type) {
    CarState_ButtonEvent_Type[CarState_ButtonEvent_Type["UNKNOWN"] = 0] = "UNKNOWN";
    CarState_ButtonEvent_Type[CarState_ButtonEvent_Type["LEFT_BLINKER"] = 1] = "LEFT_BLINKER";
    CarState_ButtonEvent_Type[CarState_ButtonEvent_Type["RIGHT_BLINKER"] = 2] = "RIGHT_BLINKER";
    CarState_ButtonEvent_Type[CarState_ButtonEvent_Type["ACCEL_CRUISE"] = 3] = "ACCEL_CRUISE";
    CarState_ButtonEvent_Type[CarState_ButtonEvent_Type["DECEL_CRUISE"] = 4] = "DECEL_CRUISE";
    CarState_ButtonEvent_Type[CarState_ButtonEvent_Type["CANCEL"] = 5] = "CANCEL";
    CarState_ButtonEvent_Type[CarState_ButtonEvent_Type["ALT_BUTTON1"] = 6] = "ALT_BUTTON1";
    CarState_ButtonEvent_Type[CarState_ButtonEvent_Type["ALT_BUTTON2"] = 7] = "ALT_BUTTON2";
    CarState_ButtonEvent_Type[CarState_ButtonEvent_Type["ALT_BUTTON3"] = 8] = "ALT_BUTTON3";
    CarState_ButtonEvent_Type[CarState_ButtonEvent_Type["SET_CRUISE"] = 9] = "SET_CRUISE";
    CarState_ButtonEvent_Type[CarState_ButtonEvent_Type["RESUME_CRUISE"] = 10] = "RESUME_CRUISE";
    CarState_ButtonEvent_Type[CarState_ButtonEvent_Type["GAP_ADJUST_CRUISE"] = 11] = "GAP_ADJUST_CRUISE";
})(CarState_ButtonEvent_Type = exports.CarState_ButtonEvent_Type || (exports.CarState_ButtonEvent_Type = {}));
class CarState_ButtonEvent extends capnp_ts_1.Struct {
    getPressed() { return capnp_ts_1.Struct.getBit(0, this); }
    setPressed(value) { capnp_ts_1.Struct.setBit(0, value, this); }
    getType() { return capnp_ts_1.Struct.getUint16(2, this); }
    setType(value) { capnp_ts_1.Struct.setUint16(2, value, this); }
    toString() { return "CarState_ButtonEvent_" + super.toString(); }
}
CarState_ButtonEvent.Type = CarState_ButtonEvent_Type;
CarState_ButtonEvent._capnp = { displayName: "ButtonEvent", id: "ff5ca6835b4acef6", size: new capnp_ts_1.ObjectSize(8, 0) };
exports.CarState_ButtonEvent = CarState_ButtonEvent;
class CarState extends capnp_ts_1.Struct {
    adoptEvents(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(5, this)); }
    disownEvents() { return capnp_ts_1.Struct.disown(this.getEvents()); }
    getEvents() { return capnp_ts_1.Struct.getList(5, CarState._Events, this); }
    hasEvents() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(5, this)); }
    initEvents(length) { return capnp_ts_1.Struct.initList(5, CarState._Events, length, this); }
    setEvents(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(5, this)); }
    getVEgo() { return capnp_ts_1.Struct.getFloat32(0, this); }
    setVEgo(value) { capnp_ts_1.Struct.setFloat32(0, value, this); }
    getAEgo() { return capnp_ts_1.Struct.getFloat32(28, this); }
    setAEgo(value) { capnp_ts_1.Struct.setFloat32(28, value, this); }
    getVEgoRaw() { return capnp_ts_1.Struct.getFloat32(32, this); }
    setVEgoRaw(value) { capnp_ts_1.Struct.setFloat32(32, value, this); }
    getYawRate() { return capnp_ts_1.Struct.getFloat32(36, this); }
    setYawRate(value) { capnp_ts_1.Struct.setFloat32(36, value, this); }
    getStandstill() { return capnp_ts_1.Struct.getBit(67, this); }
    setStandstill(value) { capnp_ts_1.Struct.setBit(67, value, this); }
    adoptWheelSpeeds(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(1, this)); }
    disownWheelSpeeds() { return capnp_ts_1.Struct.disown(this.getWheelSpeeds()); }
    getWheelSpeeds() { return capnp_ts_1.Struct.getStruct(1, CarState_WheelSpeeds, this); }
    hasWheelSpeeds() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(1, this)); }
    initWheelSpeeds() { return capnp_ts_1.Struct.initStructAt(1, CarState_WheelSpeeds, this); }
    setWheelSpeeds(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(1, this)); }
    getGas() { return capnp_ts_1.Struct.getFloat32(4, this); }
    setGas(value) { capnp_ts_1.Struct.setFloat32(4, value, this); }
    getGasPressed() { return capnp_ts_1.Struct.getBit(64, this); }
    setGasPressed(value) { capnp_ts_1.Struct.setBit(64, value, this); }
    getBrake() { return capnp_ts_1.Struct.getFloat32(12, this); }
    setBrake(value) { capnp_ts_1.Struct.setFloat32(12, value, this); }
    getBrakePressed() { return capnp_ts_1.Struct.getBit(65, this); }
    setBrakePressed(value) { capnp_ts_1.Struct.setBit(65, value, this); }
    getBrakeLights() { return capnp_ts_1.Struct.getBit(68, this); }
    setBrakeLights(value) { capnp_ts_1.Struct.setBit(68, value, this); }
    getSteeringAngleDeg() { return capnp_ts_1.Struct.getFloat32(16, this); }
    setSteeringAngleDeg(value) { capnp_ts_1.Struct.setFloat32(16, value, this); }
    getSteeringRateDeg() { return capnp_ts_1.Struct.getFloat32(24, this); }
    setSteeringRateDeg(value) { capnp_ts_1.Struct.setFloat32(24, value, this); }
    getSteeringTorque() { return capnp_ts_1.Struct.getFloat32(20, this); }
    setSteeringTorque(value) { capnp_ts_1.Struct.setFloat32(20, value, this); }
    getSteeringTorqueEps() { return capnp_ts_1.Struct.getFloat32(40, this); }
    setSteeringTorqueEps(value) { capnp_ts_1.Struct.setFloat32(40, value, this); }
    getSteeringPressed() { return capnp_ts_1.Struct.getBit(66, this); }
    setSteeringPressed(value) { capnp_ts_1.Struct.setBit(66, value, this); }
    getSteeringRateLimited() { return capnp_ts_1.Struct.getBit(76, this); }
    setSteeringRateLimited(value) { capnp_ts_1.Struct.setBit(76, value, this); }
    getSteerWarning() { return capnp_ts_1.Struct.getBit(354, this); }
    setSteerWarning(value) { capnp_ts_1.Struct.setBit(354, value, this); }
    getSteerError() { return capnp_ts_1.Struct.getBit(355, this); }
    setSteerError(value) { capnp_ts_1.Struct.setBit(355, value, this); }
    getStockAeb() { return capnp_ts_1.Struct.getBit(77, this); }
    setStockAeb(value) { capnp_ts_1.Struct.setBit(77, value, this); }
    getStockFcw() { return capnp_ts_1.Struct.getBit(78, this); }
    setStockFcw(value) { capnp_ts_1.Struct.setBit(78, value, this); }
    getEspDisabled() { return capnp_ts_1.Struct.getBit(79, this); }
    setEspDisabled(value) { capnp_ts_1.Struct.setBit(79, value, this); }
    adoptCruiseState(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(2, this)); }
    disownCruiseState() { return capnp_ts_1.Struct.disown(this.getCruiseState()); }
    getCruiseState() { return capnp_ts_1.Struct.getStruct(2, CarState_CruiseState, this); }
    hasCruiseState() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(2, this)); }
    initCruiseState() { return capnp_ts_1.Struct.initStructAt(2, CarState_CruiseState, this); }
    setCruiseState(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(2, this)); }
    getGearShifter() { return capnp_ts_1.Struct.getUint16(10, this); }
    setGearShifter(value) { capnp_ts_1.Struct.setUint16(10, value, this); }
    adoptButtonEvents(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(3, this)); }
    disownButtonEvents() { return capnp_ts_1.Struct.disown(this.getButtonEvents()); }
    getButtonEvents() { return capnp_ts_1.Struct.getList(3, CarState._ButtonEvents, this); }
    hasButtonEvents() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(3, this)); }
    initButtonEvents(length) { return capnp_ts_1.Struct.initList(3, CarState._ButtonEvents, length, this); }
    setButtonEvents(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(3, this)); }
    getLeftBlinker() { return capnp_ts_1.Struct.getBit(69, this); }
    setLeftBlinker(value) { capnp_ts_1.Struct.setBit(69, value, this); }
    getRightBlinker() { return capnp_ts_1.Struct.getBit(70, this); }
    setRightBlinker(value) { capnp_ts_1.Struct.setBit(70, value, this); }
    getGenericToggle() { return capnp_ts_1.Struct.getBit(71, this); }
    setGenericToggle(value) { capnp_ts_1.Struct.setBit(71, value, this); }
    getDoorOpen() { return capnp_ts_1.Struct.getBit(72, this); }
    setDoorOpen(value) { capnp_ts_1.Struct.setBit(72, value, this); }
    getSeatbeltUnlatched() { return capnp_ts_1.Struct.getBit(73, this); }
    setSeatbeltUnlatched(value) { capnp_ts_1.Struct.setBit(73, value, this); }
    getCanValid() { return capnp_ts_1.Struct.getBit(74, this); }
    setCanValid(value) { capnp_ts_1.Struct.setBit(74, value, this); }
    getClutchPressed() { return capnp_ts_1.Struct.getBit(75, this); }
    setClutchPressed(value) { capnp_ts_1.Struct.setBit(75, value, this); }
    adoptCanMonoTimes(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(4, this)); }
    disownCanMonoTimes() { return capnp_ts_1.Struct.disown(this.getCanMonoTimes()); }
    getCanMonoTimes() { return capnp_ts_1.Struct.getList(4, capnp.Uint64List, this); }
    hasCanMonoTimes() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(4, this)); }
    initCanMonoTimes(length) { return capnp_ts_1.Struct.initList(4, capnp.Uint64List, length, this); }
    setCanMonoTimes(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(4, this)); }
    getLeftBlindspot() { return capnp_ts_1.Struct.getBit(352, this); }
    setLeftBlindspot(value) { capnp_ts_1.Struct.setBit(352, value, this); }
    getRightBlindspot() { return capnp_ts_1.Struct.getBit(353, this); }
    setRightBlindspot(value) { capnp_ts_1.Struct.setBit(353, value, this); }
    adoptErrorsDEPRECATED(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this)); }
    disownErrorsDEPRECATED() { return capnp_ts_1.Struct.disown(this.getErrorsDEPRECATED()); }
    getErrorsDEPRECATED() { return capnp_ts_1.Struct.getList(0, capnp.Uint16List, this); }
    hasErrorsDEPRECATED() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initErrorsDEPRECATED(length) { return capnp_ts_1.Struct.initList(0, capnp.Uint16List, length, this); }
    setErrorsDEPRECATED(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this)); }
    toString() { return "CarState_" + super.toString(); }
}
CarState.WheelSpeeds = CarState_WheelSpeeds;
CarState.CruiseState = CarState_CruiseState;
CarState.GearShifter = CarState_GearShifter;
CarState.ButtonEvent = CarState_ButtonEvent;
CarState._capnp = { displayName: "CarState", id: "9da4fa09e052903c", size: new capnp_ts_1.ObjectSize(48, 6) };
exports.CarState = CarState;
var RadarData_Error;
(function (RadarData_Error) {
    RadarData_Error[RadarData_Error["CAN_ERROR"] = 0] = "CAN_ERROR";
    RadarData_Error[RadarData_Error["FAULT"] = 1] = "FAULT";
    RadarData_Error[RadarData_Error["WRONG_CONFIG"] = 2] = "WRONG_CONFIG";
})(RadarData_Error = exports.RadarData_Error || (exports.RadarData_Error = {}));
class RadarData_RadarPoint extends capnp_ts_1.Struct {
    getTrackId() { return capnp_ts_1.Struct.getUint64(0, this); }
    setTrackId(value) { capnp_ts_1.Struct.setUint64(0, value, this); }
    getDRel() { return capnp_ts_1.Struct.getFloat32(8, this); }
    setDRel(value) { capnp_ts_1.Struct.setFloat32(8, value, this); }
    getYRel() { return capnp_ts_1.Struct.getFloat32(12, this); }
    setYRel(value) { capnp_ts_1.Struct.setFloat32(12, value, this); }
    getVRel() { return capnp_ts_1.Struct.getFloat32(16, this); }
    setVRel(value) { capnp_ts_1.Struct.setFloat32(16, value, this); }
    getARel() { return capnp_ts_1.Struct.getFloat32(20, this); }
    setARel(value) { capnp_ts_1.Struct.setFloat32(20, value, this); }
    getYvRel() { return capnp_ts_1.Struct.getFloat32(24, this); }
    setYvRel(value) { capnp_ts_1.Struct.setFloat32(24, value, this); }
    getMeasured() { return capnp_ts_1.Struct.getBit(224, this); }
    setMeasured(value) { capnp_ts_1.Struct.setBit(224, value, this); }
    toString() { return "RadarData_RadarPoint_" + super.toString(); }
}
RadarData_RadarPoint._capnp = { displayName: "RadarPoint", id: "8ff333ebac1fdf36", size: new capnp_ts_1.ObjectSize(32, 0) };
exports.RadarData_RadarPoint = RadarData_RadarPoint;
class RadarData extends capnp_ts_1.Struct {
    adoptErrors(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this)); }
    disownErrors() { return capnp_ts_1.Struct.disown(this.getErrors()); }
    getErrors() { return capnp_ts_1.Struct.getList(0, capnp.Uint16List, this); }
    hasErrors() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initErrors(length) { return capnp_ts_1.Struct.initList(0, capnp.Uint16List, length, this); }
    setErrors(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this)); }
    adoptPoints(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(1, this)); }
    disownPoints() { return capnp_ts_1.Struct.disown(this.getPoints()); }
    getPoints() { return capnp_ts_1.Struct.getList(1, RadarData._Points, this); }
    hasPoints() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(1, this)); }
    initPoints(length) { return capnp_ts_1.Struct.initList(1, RadarData._Points, length, this); }
    setPoints(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(1, this)); }
    adoptCanMonoTimes(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(2, this)); }
    disownCanMonoTimes() { return capnp_ts_1.Struct.disown(this.getCanMonoTimes()); }
    getCanMonoTimes() { return capnp_ts_1.Struct.getList(2, capnp.Uint64List, this); }
    hasCanMonoTimes() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(2, this)); }
    initCanMonoTimes(length) { return capnp_ts_1.Struct.initList(2, capnp.Uint64List, length, this); }
    setCanMonoTimes(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(2, this)); }
    toString() { return "RadarData_" + super.toString(); }
}
RadarData.Error = RadarData_Error;
RadarData.RadarPoint = RadarData_RadarPoint;
RadarData._capnp = { displayName: "RadarData", id: "888ad6581cf0aacb", size: new capnp_ts_1.ObjectSize(0, 3) };
exports.RadarData = RadarData;
class CarControl_Actuators extends capnp_ts_1.Struct {
    getGas() { return capnp_ts_1.Struct.getFloat32(0, this); }
    setGas(value) { capnp_ts_1.Struct.setFloat32(0, value, this); }
    getBrake() { return capnp_ts_1.Struct.getFloat32(4, this); }
    setBrake(value) { capnp_ts_1.Struct.setFloat32(4, value, this); }
    getSteer() { return capnp_ts_1.Struct.getFloat32(8, this); }
    setSteer(value) { capnp_ts_1.Struct.setFloat32(8, value, this); }
    getSteeringAngleDeg() { return capnp_ts_1.Struct.getFloat32(12, this); }
    setSteeringAngleDeg(value) { capnp_ts_1.Struct.setFloat32(12, value, this); }
    toString() { return "CarControl_Actuators_" + super.toString(); }
}
CarControl_Actuators._capnp = { displayName: "Actuators", id: "e97275a919432828", size: new capnp_ts_1.ObjectSize(16, 0) };
exports.CarControl_Actuators = CarControl_Actuators;
class CarControl_CruiseControl extends capnp_ts_1.Struct {
    getCancel() { return capnp_ts_1.Struct.getBit(0, this); }
    setCancel(value) { capnp_ts_1.Struct.setBit(0, value, this); }
    getOverride() { return capnp_ts_1.Struct.getBit(1, this); }
    setOverride(value) { capnp_ts_1.Struct.setBit(1, value, this); }
    getSpeedOverride() { return capnp_ts_1.Struct.getFloat32(4, this); }
    setSpeedOverride(value) { capnp_ts_1.Struct.setFloat32(4, value, this); }
    getAccelOverride() { return capnp_ts_1.Struct.getFloat32(8, this); }
    setAccelOverride(value) { capnp_ts_1.Struct.setFloat32(8, value, this); }
    toString() { return "CarControl_CruiseControl_" + super.toString(); }
}
CarControl_CruiseControl._capnp = { displayName: "CruiseControl", id: "b20e386e0e0ba8d3", size: new capnp_ts_1.ObjectSize(16, 0) };
exports.CarControl_CruiseControl = CarControl_CruiseControl;
var CarControl_HUDControl_VisualAlert;
(function (CarControl_HUDControl_VisualAlert) {
    CarControl_HUDControl_VisualAlert[CarControl_HUDControl_VisualAlert["NONE"] = 0] = "NONE";
    CarControl_HUDControl_VisualAlert[CarControl_HUDControl_VisualAlert["FCW"] = 1] = "FCW";
    CarControl_HUDControl_VisualAlert[CarControl_HUDControl_VisualAlert["STEER_REQUIRED"] = 2] = "STEER_REQUIRED";
    CarControl_HUDControl_VisualAlert[CarControl_HUDControl_VisualAlert["BRAKE_PRESSED"] = 3] = "BRAKE_PRESSED";
    CarControl_HUDControl_VisualAlert[CarControl_HUDControl_VisualAlert["WRONG_GEAR"] = 4] = "WRONG_GEAR";
    CarControl_HUDControl_VisualAlert[CarControl_HUDControl_VisualAlert["SEATBELT_UNBUCKLED"] = 5] = "SEATBELT_UNBUCKLED";
    CarControl_HUDControl_VisualAlert[CarControl_HUDControl_VisualAlert["SPEED_TOO_HIGH"] = 6] = "SPEED_TOO_HIGH";
    CarControl_HUDControl_VisualAlert[CarControl_HUDControl_VisualAlert["LDW"] = 7] = "LDW";
})(CarControl_HUDControl_VisualAlert = exports.CarControl_HUDControl_VisualAlert || (exports.CarControl_HUDControl_VisualAlert = {}));
var CarControl_HUDControl_AudibleAlert;
(function (CarControl_HUDControl_AudibleAlert) {
    CarControl_HUDControl_AudibleAlert[CarControl_HUDControl_AudibleAlert["NONE"] = 0] = "NONE";
    CarControl_HUDControl_AudibleAlert[CarControl_HUDControl_AudibleAlert["CHIME_ENGAGE"] = 1] = "CHIME_ENGAGE";
    CarControl_HUDControl_AudibleAlert[CarControl_HUDControl_AudibleAlert["CHIME_DISENGAGE"] = 2] = "CHIME_DISENGAGE";
    CarControl_HUDControl_AudibleAlert[CarControl_HUDControl_AudibleAlert["CHIME_ERROR"] = 3] = "CHIME_ERROR";
    CarControl_HUDControl_AudibleAlert[CarControl_HUDControl_AudibleAlert["CHIME_WARNING1"] = 4] = "CHIME_WARNING1";
    CarControl_HUDControl_AudibleAlert[CarControl_HUDControl_AudibleAlert["CHIME_WARNING2"] = 5] = "CHIME_WARNING2";
    CarControl_HUDControl_AudibleAlert[CarControl_HUDControl_AudibleAlert["CHIME_WARNING_REPEAT"] = 6] = "CHIME_WARNING_REPEAT";
    CarControl_HUDControl_AudibleAlert[CarControl_HUDControl_AudibleAlert["CHIME_PROMPT"] = 7] = "CHIME_PROMPT";
    CarControl_HUDControl_AudibleAlert[CarControl_HUDControl_AudibleAlert["CHIME_WARNING2REPEAT"] = 8] = "CHIME_WARNING2REPEAT";
})(CarControl_HUDControl_AudibleAlert = exports.CarControl_HUDControl_AudibleAlert || (exports.CarControl_HUDControl_AudibleAlert = {}));
class CarControl_HUDControl extends capnp_ts_1.Struct {
    getSpeedVisible() { return capnp_ts_1.Struct.getBit(0, this); }
    setSpeedVisible(value) { capnp_ts_1.Struct.setBit(0, value, this); }
    getSetSpeed() { return capnp_ts_1.Struct.getFloat32(4, this); }
    setSetSpeed(value) { capnp_ts_1.Struct.setFloat32(4, value, this); }
    getLanesVisible() { return capnp_ts_1.Struct.getBit(1, this); }
    setLanesVisible(value) { capnp_ts_1.Struct.setBit(1, value, this); }
    getLeadVisible() { return capnp_ts_1.Struct.getBit(2, this); }
    setLeadVisible(value) { capnp_ts_1.Struct.setBit(2, value, this); }
    getVisualAlert() { return capnp_ts_1.Struct.getUint16(2, this); }
    setVisualAlert(value) { capnp_ts_1.Struct.setUint16(2, value, this); }
    getAudibleAlert() { return capnp_ts_1.Struct.getUint16(8, this); }
    setAudibleAlert(value) { capnp_ts_1.Struct.setUint16(8, value, this); }
    getRightLaneVisible() { return capnp_ts_1.Struct.getBit(3, this); }
    setRightLaneVisible(value) { capnp_ts_1.Struct.setBit(3, value, this); }
    getLeftLaneVisible() { return capnp_ts_1.Struct.getBit(4, this); }
    setLeftLaneVisible(value) { capnp_ts_1.Struct.setBit(4, value, this); }
    getRightLaneDepart() { return capnp_ts_1.Struct.getBit(5, this); }
    setRightLaneDepart(value) { capnp_ts_1.Struct.setBit(5, value, this); }
    getLeftLaneDepart() { return capnp_ts_1.Struct.getBit(6, this); }
    setLeftLaneDepart(value) { capnp_ts_1.Struct.setBit(6, value, this); }
    toString() { return "CarControl_HUDControl_" + super.toString(); }
}
CarControl_HUDControl.VisualAlert = CarControl_HUDControl_VisualAlert;
CarControl_HUDControl.AudibleAlert = CarControl_HUDControl_AudibleAlert;
CarControl_HUDControl._capnp = { displayName: "HUDControl", id: "d895c87c4eb03a38", size: new capnp_ts_1.ObjectSize(16, 0) };
exports.CarControl_HUDControl = CarControl_HUDControl;
class CarControl extends capnp_ts_1.Struct {
    getEnabled() { return capnp_ts_1.Struct.getBit(0, this); }
    setEnabled(value) { capnp_ts_1.Struct.setBit(0, value, this); }
    getActive() { return capnp_ts_1.Struct.getBit(1, this); }
    setActive(value) { capnp_ts_1.Struct.setBit(1, value, this); }
    adoptActuators(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(2, this)); }
    disownActuators() { return capnp_ts_1.Struct.disown(this.getActuators()); }
    getActuators() { return capnp_ts_1.Struct.getStruct(2, CarControl_Actuators, this); }
    hasActuators() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(2, this)); }
    initActuators() { return capnp_ts_1.Struct.initStructAt(2, CarControl_Actuators, this); }
    setActuators(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(2, this)); }
    adoptCruiseControl(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this)); }
    disownCruiseControl() { return capnp_ts_1.Struct.disown(this.getCruiseControl()); }
    getCruiseControl() { return capnp_ts_1.Struct.getStruct(0, CarControl_CruiseControl, this); }
    hasCruiseControl() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initCruiseControl() { return capnp_ts_1.Struct.initStructAt(0, CarControl_CruiseControl, this); }
    setCruiseControl(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this)); }
    adoptHudControl(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(1, this)); }
    disownHudControl() { return capnp_ts_1.Struct.disown(this.getHudControl()); }
    getHudControl() { return capnp_ts_1.Struct.getStruct(1, CarControl_HUDControl, this); }
    hasHudControl() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(1, this)); }
    initHudControl() { return capnp_ts_1.Struct.initStructAt(1, CarControl_HUDControl, this); }
    setHudControl(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(1, this)); }
    getGasDEPRECATED() { return capnp_ts_1.Struct.getFloat32(4, this); }
    setGasDEPRECATED(value) { capnp_ts_1.Struct.setFloat32(4, value, this); }
    getBrakeDEPRECATED() { return capnp_ts_1.Struct.getFloat32(8, this); }
    setBrakeDEPRECATED(value) { capnp_ts_1.Struct.setFloat32(8, value, this); }
    getSteeringTorqueDEPRECATED() { return capnp_ts_1.Struct.getFloat32(12, this); }
    setSteeringTorqueDEPRECATED(value) { capnp_ts_1.Struct.setFloat32(12, value, this); }
    toString() { return "CarControl_" + super.toString(); }
}
CarControl.Actuators = CarControl_Actuators;
CarControl.CruiseControl = CarControl_CruiseControl;
CarControl.HUDControl = CarControl_HUDControl;
CarControl._capnp = { displayName: "CarControl", id: "f78829049ab814af", size: new capnp_ts_1.ObjectSize(16, 3) };
exports.CarControl = CarControl;
class CarParams_LateralParams extends capnp_ts_1.Struct {
    adoptTorqueBP(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this)); }
    disownTorqueBP() { return capnp_ts_1.Struct.disown(this.getTorqueBP()); }
    getTorqueBP() { return capnp_ts_1.Struct.getList(0, capnp.Int32List, this); }
    hasTorqueBP() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initTorqueBP(length) { return capnp_ts_1.Struct.initList(0, capnp.Int32List, length, this); }
    setTorqueBP(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this)); }
    adoptTorqueV(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(1, this)); }
    disownTorqueV() { return capnp_ts_1.Struct.disown(this.getTorqueV()); }
    getTorqueV() { return capnp_ts_1.Struct.getList(1, capnp.Int32List, this); }
    hasTorqueV() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(1, this)); }
    initTorqueV(length) { return capnp_ts_1.Struct.initList(1, capnp.Int32List, length, this); }
    setTorqueV(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(1, this)); }
    toString() { return "CarParams_LateralParams_" + super.toString(); }
}
CarParams_LateralParams._capnp = { displayName: "LateralParams", id: "b581b23b1c89dda3", size: new capnp_ts_1.ObjectSize(0, 2) };
exports.CarParams_LateralParams = CarParams_LateralParams;
class CarParams_LateralPIDTuning extends capnp_ts_1.Struct {
    adoptKpBP(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this)); }
    disownKpBP() { return capnp_ts_1.Struct.disown(this.getKpBP()); }
    getKpBP() { return capnp_ts_1.Struct.getList(0, capnp.Float32List, this); }
    hasKpBP() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initKpBP(length) { return capnp_ts_1.Struct.initList(0, capnp.Float32List, length, this); }
    setKpBP(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this)); }
    adoptKpV(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(1, this)); }
    disownKpV() { return capnp_ts_1.Struct.disown(this.getKpV()); }
    getKpV() { return capnp_ts_1.Struct.getList(1, capnp.Float32List, this); }
    hasKpV() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(1, this)); }
    initKpV(length) { return capnp_ts_1.Struct.initList(1, capnp.Float32List, length, this); }
    setKpV(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(1, this)); }
    adoptKiBP(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(2, this)); }
    disownKiBP() { return capnp_ts_1.Struct.disown(this.getKiBP()); }
    getKiBP() { return capnp_ts_1.Struct.getList(2, capnp.Float32List, this); }
    hasKiBP() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(2, this)); }
    initKiBP(length) { return capnp_ts_1.Struct.initList(2, capnp.Float32List, length, this); }
    setKiBP(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(2, this)); }
    adoptKiV(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(3, this)); }
    disownKiV() { return capnp_ts_1.Struct.disown(this.getKiV()); }
    getKiV() { return capnp_ts_1.Struct.getList(3, capnp.Float32List, this); }
    hasKiV() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(3, this)); }
    initKiV(length) { return capnp_ts_1.Struct.initList(3, capnp.Float32List, length, this); }
    setKiV(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(3, this)); }
    getKf() { return capnp_ts_1.Struct.getFloat32(0, this); }
    setKf(value) { capnp_ts_1.Struct.setFloat32(0, value, this); }
    toString() { return "CarParams_LateralPIDTuning_" + super.toString(); }
}
CarParams_LateralPIDTuning._capnp = { displayName: "LateralPIDTuning", id: "9622723fcbd14c2e", size: new capnp_ts_1.ObjectSize(8, 4) };
exports.CarParams_LateralPIDTuning = CarParams_LateralPIDTuning;
class CarParams_LongitudinalPIDTuning extends capnp_ts_1.Struct {
    adoptKpBP(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this)); }
    disownKpBP() { return capnp_ts_1.Struct.disown(this.getKpBP()); }
    getKpBP() { return capnp_ts_1.Struct.getList(0, capnp.Float32List, this); }
    hasKpBP() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initKpBP(length) { return capnp_ts_1.Struct.initList(0, capnp.Float32List, length, this); }
    setKpBP(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this)); }
    adoptKpV(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(1, this)); }
    disownKpV() { return capnp_ts_1.Struct.disown(this.getKpV()); }
    getKpV() { return capnp_ts_1.Struct.getList(1, capnp.Float32List, this); }
    hasKpV() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(1, this)); }
    initKpV(length) { return capnp_ts_1.Struct.initList(1, capnp.Float32List, length, this); }
    setKpV(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(1, this)); }
    adoptKiBP(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(2, this)); }
    disownKiBP() { return capnp_ts_1.Struct.disown(this.getKiBP()); }
    getKiBP() { return capnp_ts_1.Struct.getList(2, capnp.Float32List, this); }
    hasKiBP() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(2, this)); }
    initKiBP(length) { return capnp_ts_1.Struct.initList(2, capnp.Float32List, length, this); }
    setKiBP(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(2, this)); }
    adoptKiV(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(3, this)); }
    disownKiV() { return capnp_ts_1.Struct.disown(this.getKiV()); }
    getKiV() { return capnp_ts_1.Struct.getList(3, capnp.Float32List, this); }
    hasKiV() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(3, this)); }
    initKiV(length) { return capnp_ts_1.Struct.initList(3, capnp.Float32List, length, this); }
    setKiV(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(3, this)); }
    adoptDeadzoneBP(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(4, this)); }
    disownDeadzoneBP() { return capnp_ts_1.Struct.disown(this.getDeadzoneBP()); }
    getDeadzoneBP() { return capnp_ts_1.Struct.getList(4, capnp.Float32List, this); }
    hasDeadzoneBP() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(4, this)); }
    initDeadzoneBP(length) { return capnp_ts_1.Struct.initList(4, capnp.Float32List, length, this); }
    setDeadzoneBP(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(4, this)); }
    adoptDeadzoneV(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(5, this)); }
    disownDeadzoneV() { return capnp_ts_1.Struct.disown(this.getDeadzoneV()); }
    getDeadzoneV() { return capnp_ts_1.Struct.getList(5, capnp.Float32List, this); }
    hasDeadzoneV() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(5, this)); }
    initDeadzoneV(length) { return capnp_ts_1.Struct.initList(5, capnp.Float32List, length, this); }
    setDeadzoneV(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(5, this)); }
    toString() { return "CarParams_LongitudinalPIDTuning_" + super.toString(); }
}
CarParams_LongitudinalPIDTuning._capnp = { displayName: "LongitudinalPIDTuning", id: "c342cefc303e9b8e", size: new capnp_ts_1.ObjectSize(0, 6) };
exports.CarParams_LongitudinalPIDTuning = CarParams_LongitudinalPIDTuning;
class CarParams_LateralINDITuning extends capnp_ts_1.Struct {
    adoptOuterLoopGainBP(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this)); }
    disownOuterLoopGainBP() { return capnp_ts_1.Struct.disown(this.getOuterLoopGainBP()); }
    getOuterLoopGainBP() { return capnp_ts_1.Struct.getList(0, capnp.Float32List, this); }
    hasOuterLoopGainBP() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initOuterLoopGainBP(length) { return capnp_ts_1.Struct.initList(0, capnp.Float32List, length, this); }
    setOuterLoopGainBP(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this)); }
    adoptOuterLoopGainV(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(1, this)); }
    disownOuterLoopGainV() { return capnp_ts_1.Struct.disown(this.getOuterLoopGainV()); }
    getOuterLoopGainV() { return capnp_ts_1.Struct.getList(1, capnp.Float32List, this); }
    hasOuterLoopGainV() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(1, this)); }
    initOuterLoopGainV(length) { return capnp_ts_1.Struct.initList(1, capnp.Float32List, length, this); }
    setOuterLoopGainV(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(1, this)); }
    adoptInnerLoopGainBP(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(2, this)); }
    disownInnerLoopGainBP() { return capnp_ts_1.Struct.disown(this.getInnerLoopGainBP()); }
    getInnerLoopGainBP() { return capnp_ts_1.Struct.getList(2, capnp.Float32List, this); }
    hasInnerLoopGainBP() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(2, this)); }
    initInnerLoopGainBP(length) { return capnp_ts_1.Struct.initList(2, capnp.Float32List, length, this); }
    setInnerLoopGainBP(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(2, this)); }
    adoptInnerLoopGainV(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(3, this)); }
    disownInnerLoopGainV() { return capnp_ts_1.Struct.disown(this.getInnerLoopGainV()); }
    getInnerLoopGainV() { return capnp_ts_1.Struct.getList(3, capnp.Float32List, this); }
    hasInnerLoopGainV() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(3, this)); }
    initInnerLoopGainV(length) { return capnp_ts_1.Struct.initList(3, capnp.Float32List, length, this); }
    setInnerLoopGainV(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(3, this)); }
    adoptTimeConstantBP(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(4, this)); }
    disownTimeConstantBP() { return capnp_ts_1.Struct.disown(this.getTimeConstantBP()); }
    getTimeConstantBP() { return capnp_ts_1.Struct.getList(4, capnp.Float32List, this); }
    hasTimeConstantBP() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(4, this)); }
    initTimeConstantBP(length) { return capnp_ts_1.Struct.initList(4, capnp.Float32List, length, this); }
    setTimeConstantBP(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(4, this)); }
    adoptTimeConstantV(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(5, this)); }
    disownTimeConstantV() { return capnp_ts_1.Struct.disown(this.getTimeConstantV()); }
    getTimeConstantV() { return capnp_ts_1.Struct.getList(5, capnp.Float32List, this); }
    hasTimeConstantV() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(5, this)); }
    initTimeConstantV(length) { return capnp_ts_1.Struct.initList(5, capnp.Float32List, length, this); }
    setTimeConstantV(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(5, this)); }
    adoptActuatorEffectivenessBP(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(6, this)); }
    disownActuatorEffectivenessBP() { return capnp_ts_1.Struct.disown(this.getActuatorEffectivenessBP()); }
    getActuatorEffectivenessBP() { return capnp_ts_1.Struct.getList(6, capnp.Float32List, this); }
    hasActuatorEffectivenessBP() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(6, this)); }
    initActuatorEffectivenessBP(length) { return capnp_ts_1.Struct.initList(6, capnp.Float32List, length, this); }
    setActuatorEffectivenessBP(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(6, this)); }
    adoptActuatorEffectivenessV(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(7, this)); }
    disownActuatorEffectivenessV() { return capnp_ts_1.Struct.disown(this.getActuatorEffectivenessV()); }
    getActuatorEffectivenessV() { return capnp_ts_1.Struct.getList(7, capnp.Float32List, this); }
    hasActuatorEffectivenessV() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(7, this)); }
    initActuatorEffectivenessV(length) { return capnp_ts_1.Struct.initList(7, capnp.Float32List, length, this); }
    setActuatorEffectivenessV(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(7, this)); }
    getOuterLoopGainDEPRECATED() { return capnp_ts_1.Struct.getFloat32(0, this); }
    setOuterLoopGainDEPRECATED(value) { capnp_ts_1.Struct.setFloat32(0, value, this); }
    getInnerLoopGainDEPRECATED() { return capnp_ts_1.Struct.getFloat32(4, this); }
    setInnerLoopGainDEPRECATED(value) { capnp_ts_1.Struct.setFloat32(4, value, this); }
    getTimeConstantDEPRECATED() { return capnp_ts_1.Struct.getFloat32(8, this); }
    setTimeConstantDEPRECATED(value) { capnp_ts_1.Struct.setFloat32(8, value, this); }
    getActuatorEffectivenessDEPRECATED() { return capnp_ts_1.Struct.getFloat32(12, this); }
    setActuatorEffectivenessDEPRECATED(value) { capnp_ts_1.Struct.setFloat32(12, value, this); }
    toString() { return "CarParams_LateralINDITuning_" + super.toString(); }
}
CarParams_LateralINDITuning._capnp = { displayName: "LateralINDITuning", id: "a334472e045533b3", size: new capnp_ts_1.ObjectSize(16, 8) };
exports.CarParams_LateralINDITuning = CarParams_LateralINDITuning;
class CarParams_LateralLQRTuning extends capnp_ts_1.Struct {
    getScale() { return capnp_ts_1.Struct.getFloat32(0, this); }
    setScale(value) { capnp_ts_1.Struct.setFloat32(0, value, this); }
    getKi() { return capnp_ts_1.Struct.getFloat32(4, this); }
    setKi(value) { capnp_ts_1.Struct.setFloat32(4, value, this); }
    getDcGain() { return capnp_ts_1.Struct.getFloat32(8, this); }
    setDcGain(value) { capnp_ts_1.Struct.setFloat32(8, value, this); }
    adoptA(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this)); }
    disownA() { return capnp_ts_1.Struct.disown(this.getA()); }
    getA() { return capnp_ts_1.Struct.getList(0, capnp.Float32List, this); }
    hasA() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initA(length) { return capnp_ts_1.Struct.initList(0, capnp.Float32List, length, this); }
    setA(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this)); }
    adoptB(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(1, this)); }
    disownB() { return capnp_ts_1.Struct.disown(this.getB()); }
    getB() { return capnp_ts_1.Struct.getList(1, capnp.Float32List, this); }
    hasB() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(1, this)); }
    initB(length) { return capnp_ts_1.Struct.initList(1, capnp.Float32List, length, this); }
    setB(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(1, this)); }
    adoptC(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(2, this)); }
    disownC() { return capnp_ts_1.Struct.disown(this.getC()); }
    getC() { return capnp_ts_1.Struct.getList(2, capnp.Float32List, this); }
    hasC() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(2, this)); }
    initC(length) { return capnp_ts_1.Struct.initList(2, capnp.Float32List, length, this); }
    setC(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(2, this)); }
    adoptK(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(3, this)); }
    disownK() { return capnp_ts_1.Struct.disown(this.getK()); }
    getK() { return capnp_ts_1.Struct.getList(3, capnp.Float32List, this); }
    hasK() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(3, this)); }
    initK(length) { return capnp_ts_1.Struct.initList(3, capnp.Float32List, length, this); }
    setK(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(3, this)); }
    adoptL(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(4, this)); }
    disownL() { return capnp_ts_1.Struct.disown(this.getL()); }
    getL() { return capnp_ts_1.Struct.getList(4, capnp.Float32List, this); }
    hasL() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(4, this)); }
    initL(length) { return capnp_ts_1.Struct.initList(4, capnp.Float32List, length, this); }
    setL(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(4, this)); }
    toString() { return "CarParams_LateralLQRTuning_" + super.toString(); }
}
CarParams_LateralLQRTuning._capnp = { displayName: "LateralLQRTuning", id: "9d151e3f28616a12", size: new capnp_ts_1.ObjectSize(16, 5) };
exports.CarParams_LateralLQRTuning = CarParams_LateralLQRTuning;
var CarParams_SafetyModel;
(function (CarParams_SafetyModel) {
    CarParams_SafetyModel[CarParams_SafetyModel["SILENT"] = 0] = "SILENT";
    CarParams_SafetyModel[CarParams_SafetyModel["HONDA_NIDEC"] = 1] = "HONDA_NIDEC";
    CarParams_SafetyModel[CarParams_SafetyModel["TOYOTA"] = 2] = "TOYOTA";
    CarParams_SafetyModel[CarParams_SafetyModel["ELM327"] = 3] = "ELM327";
    CarParams_SafetyModel[CarParams_SafetyModel["GM"] = 4] = "GM";
    CarParams_SafetyModel[CarParams_SafetyModel["HONDA_BOSCH_GIRAFFE"] = 5] = "HONDA_BOSCH_GIRAFFE";
    CarParams_SafetyModel[CarParams_SafetyModel["FORD"] = 6] = "FORD";
    CarParams_SafetyModel[CarParams_SafetyModel["CADILLAC"] = 7] = "CADILLAC";
    CarParams_SafetyModel[CarParams_SafetyModel["HYUNDAI"] = 8] = "HYUNDAI";
    CarParams_SafetyModel[CarParams_SafetyModel["CHRYSLER"] = 9] = "CHRYSLER";
    CarParams_SafetyModel[CarParams_SafetyModel["TESLA"] = 10] = "TESLA";
    CarParams_SafetyModel[CarParams_SafetyModel["SUBARU"] = 11] = "SUBARU";
    CarParams_SafetyModel[CarParams_SafetyModel["GM_PASSIVE"] = 12] = "GM_PASSIVE";
    CarParams_SafetyModel[CarParams_SafetyModel["MAZDA"] = 13] = "MAZDA";
    CarParams_SafetyModel[CarParams_SafetyModel["NISSAN"] = 14] = "NISSAN";
    CarParams_SafetyModel[CarParams_SafetyModel["VOLKSWAGEN"] = 15] = "VOLKSWAGEN";
    CarParams_SafetyModel[CarParams_SafetyModel["TOYOTA_IPAS"] = 16] = "TOYOTA_IPAS";
    CarParams_SafetyModel[CarParams_SafetyModel["ALL_OUTPUT"] = 17] = "ALL_OUTPUT";
    CarParams_SafetyModel[CarParams_SafetyModel["GM_ASCM"] = 18] = "GM_ASCM";
    CarParams_SafetyModel[CarParams_SafetyModel["NO_OUTPUT"] = 19] = "NO_OUTPUT";
    CarParams_SafetyModel[CarParams_SafetyModel["HONDA_BOSCH_HARNESS"] = 20] = "HONDA_BOSCH_HARNESS";
    CarParams_SafetyModel[CarParams_SafetyModel["VOLKSWAGEN_PQ"] = 21] = "VOLKSWAGEN_PQ";
    CarParams_SafetyModel[CarParams_SafetyModel["SUBARU_LEGACY"] = 22] = "SUBARU_LEGACY";
    CarParams_SafetyModel[CarParams_SafetyModel["HYUNDAI_LEGACY"] = 23] = "HYUNDAI_LEGACY";
    CarParams_SafetyModel[CarParams_SafetyModel["HYUNDAI_COMMUNITY"] = 24] = "HYUNDAI_COMMUNITY";
})(CarParams_SafetyModel = exports.CarParams_SafetyModel || (exports.CarParams_SafetyModel = {}));
var CarParams_SteerControlType;
(function (CarParams_SteerControlType) {
    CarParams_SteerControlType[CarParams_SteerControlType["TORQUE"] = 0] = "TORQUE";
    CarParams_SteerControlType[CarParams_SteerControlType["ANGLE"] = 1] = "ANGLE";
})(CarParams_SteerControlType = exports.CarParams_SteerControlType || (exports.CarParams_SteerControlType = {}));
var CarParams_TransmissionType;
(function (CarParams_TransmissionType) {
    CarParams_TransmissionType[CarParams_TransmissionType["UNKNOWN"] = 0] = "UNKNOWN";
    CarParams_TransmissionType[CarParams_TransmissionType["AUTOMATIC"] = 1] = "AUTOMATIC";
    CarParams_TransmissionType[CarParams_TransmissionType["MANUAL"] = 2] = "MANUAL";
    CarParams_TransmissionType[CarParams_TransmissionType["DIRECT"] = 3] = "DIRECT";
})(CarParams_TransmissionType = exports.CarParams_TransmissionType || (exports.CarParams_TransmissionType = {}));
class CarParams_CarFw extends capnp_ts_1.Struct {
    getEcu() { return capnp_ts_1.Struct.getUint16(0, this); }
    setEcu(value) { capnp_ts_1.Struct.setUint16(0, value, this); }
    adoptFwVersion(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this)); }
    disownFwVersion() { return capnp_ts_1.Struct.disown(this.getFwVersion()); }
    getFwVersion() { return capnp_ts_1.Struct.getData(0, this); }
    hasFwVersion() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initFwVersion(length) { return capnp_ts_1.Struct.initData(0, length, this); }
    setFwVersion(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this)); }
    getAddress() { return capnp_ts_1.Struct.getUint32(4, this); }
    setAddress(value) { capnp_ts_1.Struct.setUint32(4, value, this); }
    getSubAddress() { return capnp_ts_1.Struct.getUint8(2, this); }
    setSubAddress(value) { capnp_ts_1.Struct.setUint8(2, value, this); }
    toString() { return "CarParams_CarFw_" + super.toString(); }
}
CarParams_CarFw._capnp = { displayName: "CarFw", id: "962b56180c9359ce", size: new capnp_ts_1.ObjectSize(8, 1) };
exports.CarParams_CarFw = CarParams_CarFw;
var CarParams_Ecu;
(function (CarParams_Ecu) {
    CarParams_Ecu[CarParams_Ecu["EPS"] = 0] = "EPS";
    CarParams_Ecu[CarParams_Ecu["ESP"] = 1] = "ESP";
    CarParams_Ecu[CarParams_Ecu["FWD_RADAR"] = 2] = "FWD_RADAR";
    CarParams_Ecu[CarParams_Ecu["FWD_CAMERA"] = 3] = "FWD_CAMERA";
    CarParams_Ecu[CarParams_Ecu["ENGINE"] = 4] = "ENGINE";
    CarParams_Ecu[CarParams_Ecu["UNKNOWN"] = 5] = "UNKNOWN";
    CarParams_Ecu[CarParams_Ecu["TRANSMISSION"] = 6] = "TRANSMISSION";
    CarParams_Ecu[CarParams_Ecu["SRS"] = 7] = "SRS";
    CarParams_Ecu[CarParams_Ecu["GATEWAY"] = 8] = "GATEWAY";
    CarParams_Ecu[CarParams_Ecu["HUD"] = 9] = "HUD";
    CarParams_Ecu[CarParams_Ecu["COMBINATION_METER"] = 10] = "COMBINATION_METER";
    CarParams_Ecu[CarParams_Ecu["DSU"] = 11] = "DSU";
    CarParams_Ecu[CarParams_Ecu["APGS"] = 12] = "APGS";
    CarParams_Ecu[CarParams_Ecu["VSA"] = 13] = "VSA";
    CarParams_Ecu[CarParams_Ecu["PROGRAMMED_FUEL_INJECTION"] = 14] = "PROGRAMMED_FUEL_INJECTION";
    CarParams_Ecu[CarParams_Ecu["ELECTRIC_BRAKE_BOOSTER"] = 15] = "ELECTRIC_BRAKE_BOOSTER";
    CarParams_Ecu[CarParams_Ecu["SHIFT_BY_WIRE"] = 16] = "SHIFT_BY_WIRE";
})(CarParams_Ecu = exports.CarParams_Ecu || (exports.CarParams_Ecu = {}));
var CarParams_FingerprintSource;
(function (CarParams_FingerprintSource) {
    CarParams_FingerprintSource[CarParams_FingerprintSource["CAN"] = 0] = "CAN";
    CarParams_FingerprintSource[CarParams_FingerprintSource["FW"] = 1] = "FW";
    CarParams_FingerprintSource[CarParams_FingerprintSource["FIXED"] = 2] = "FIXED";
})(CarParams_FingerprintSource = exports.CarParams_FingerprintSource || (exports.CarParams_FingerprintSource = {}));
var CarParams_NetworkLocation;
(function (CarParams_NetworkLocation) {
    CarParams_NetworkLocation[CarParams_NetworkLocation["FWD_CAMERA"] = 0] = "FWD_CAMERA";
    CarParams_NetworkLocation[CarParams_NetworkLocation["GATEWAY"] = 1] = "GATEWAY";
})(CarParams_NetworkLocation = exports.CarParams_NetworkLocation || (exports.CarParams_NetworkLocation = {}));
var CarParams_LateralTuning_Which;
(function (CarParams_LateralTuning_Which) {
    CarParams_LateralTuning_Which[CarParams_LateralTuning_Which["PID"] = 0] = "PID";
    CarParams_LateralTuning_Which[CarParams_LateralTuning_Which["INDI"] = 1] = "INDI";
    CarParams_LateralTuning_Which[CarParams_LateralTuning_Which["LQR"] = 2] = "LQR";
})(CarParams_LateralTuning_Which = exports.CarParams_LateralTuning_Which || (exports.CarParams_LateralTuning_Which = {}));
class CarParams_LateralTuning extends capnp_ts_1.Struct {
    adoptPid(value) {
        capnp_ts_1.Struct.setUint16(14, 0, this);
        capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(9, this));
    }
    disownPid() { return capnp_ts_1.Struct.disown(this.getPid()); }
    getPid() {
        capnp_ts_1.Struct.testWhich("pid", capnp_ts_1.Struct.getUint16(14, this), 0, this);
        return capnp_ts_1.Struct.getStruct(9, CarParams_LateralPIDTuning, this);
    }
    hasPid() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(9, this)); }
    initPid() {
        capnp_ts_1.Struct.setUint16(14, 0, this);
        return capnp_ts_1.Struct.initStructAt(9, CarParams_LateralPIDTuning, this);
    }
    isPid() { return capnp_ts_1.Struct.getUint16(14, this) === 0; }
    setPid(value) {
        capnp_ts_1.Struct.setUint16(14, 0, this);
        capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(9, this));
    }
    adoptIndi(value) {
        capnp_ts_1.Struct.setUint16(14, 1, this);
        capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(9, this));
    }
    disownIndi() { return capnp_ts_1.Struct.disown(this.getIndi()); }
    getIndi() {
        capnp_ts_1.Struct.testWhich("indi", capnp_ts_1.Struct.getUint16(14, this), 1, this);
        return capnp_ts_1.Struct.getStruct(9, CarParams_LateralINDITuning, this);
    }
    hasIndi() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(9, this)); }
    initIndi() {
        capnp_ts_1.Struct.setUint16(14, 1, this);
        return capnp_ts_1.Struct.initStructAt(9, CarParams_LateralINDITuning, this);
    }
    isIndi() { return capnp_ts_1.Struct.getUint16(14, this) === 1; }
    setIndi(value) {
        capnp_ts_1.Struct.setUint16(14, 1, this);
        capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(9, this));
    }
    adoptLqr(value) {
        capnp_ts_1.Struct.setUint16(14, 2, this);
        capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(9, this));
    }
    disownLqr() { return capnp_ts_1.Struct.disown(this.getLqr()); }
    getLqr() {
        capnp_ts_1.Struct.testWhich("lqr", capnp_ts_1.Struct.getUint16(14, this), 2, this);
        return capnp_ts_1.Struct.getStruct(9, CarParams_LateralLQRTuning, this);
    }
    hasLqr() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(9, this)); }
    initLqr() {
        capnp_ts_1.Struct.setUint16(14, 2, this);
        return capnp_ts_1.Struct.initStructAt(9, CarParams_LateralLQRTuning, this);
    }
    isLqr() { return capnp_ts_1.Struct.getUint16(14, this) === 2; }
    setLqr(value) {
        capnp_ts_1.Struct.setUint16(14, 2, this);
        capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(9, this));
    }
    toString() { return "CarParams_LateralTuning_" + super.toString(); }
    which() { return capnp_ts_1.Struct.getUint16(14, this); }
}
CarParams_LateralTuning.PID = CarParams_LateralTuning_Which.PID;
CarParams_LateralTuning.INDI = CarParams_LateralTuning_Which.INDI;
CarParams_LateralTuning.LQR = CarParams_LateralTuning_Which.LQR;
CarParams_LateralTuning._capnp = { displayName: "lateralTuning", id: "93fc580a35339568", size: new capnp_ts_1.ObjectSize(104, 13) };
exports.CarParams_LateralTuning = CarParams_LateralTuning;
class CarParams extends capnp_ts_1.Struct {
    getCarName() { return capnp_ts_1.Struct.getText(0, this); }
    setCarName(value) { capnp_ts_1.Struct.setText(0, value, this); }
    getCarFingerprint() { return capnp_ts_1.Struct.getText(1, this); }
    setCarFingerprint(value) { capnp_ts_1.Struct.setText(1, value, this); }
    getFuzzyFingerprint() { return capnp_ts_1.Struct.getBit(13, this); }
    setFuzzyFingerprint(value) { capnp_ts_1.Struct.setBit(13, value, this); }
    getEnableGasInterceptor() { return capnp_ts_1.Struct.getBit(0, this); }
    setEnableGasInterceptor(value) { capnp_ts_1.Struct.setBit(0, value, this); }
    getEnableCruise() { return capnp_ts_1.Struct.getBit(1, this); }
    setEnableCruise(value) { capnp_ts_1.Struct.setBit(1, value, this); }
    getEnableCamera() { return capnp_ts_1.Struct.getBit(2, this); }
    setEnableCamera(value) { capnp_ts_1.Struct.setBit(2, value, this); }
    getEnableDsu() { return capnp_ts_1.Struct.getBit(3, this); }
    setEnableDsu(value) { capnp_ts_1.Struct.setBit(3, value, this); }
    getEnableApgs() { return capnp_ts_1.Struct.getBit(4, this); }
    setEnableApgs(value) { capnp_ts_1.Struct.setBit(4, value, this); }
    getEnableBsm() { return capnp_ts_1.Struct.getBit(14, this); }
    setEnableBsm(value) { capnp_ts_1.Struct.setBit(14, value, this); }
    getMinEnableSpeed() { return capnp_ts_1.Struct.getFloat32(4, this); }
    setMinEnableSpeed(value) { capnp_ts_1.Struct.setFloat32(4, value, this); }
    getMinSteerSpeed() { return capnp_ts_1.Struct.getFloat32(8, this); }
    setMinSteerSpeed(value) { capnp_ts_1.Struct.setFloat32(8, value, this); }
    getMaxSteeringAngleDeg() { return capnp_ts_1.Struct.getFloat32(96, this); }
    setMaxSteeringAngleDeg(value) { capnp_ts_1.Struct.setFloat32(96, value, this); }
    getSafetyModel() { return capnp_ts_1.Struct.getUint16(2, this); }
    setSafetyModel(value) { capnp_ts_1.Struct.setUint16(2, value, this); }
    getSafetyModelPassive() { return capnp_ts_1.Struct.getUint16(62, this, CarParams._capnp.defaultSafetyModelPassive); }
    setSafetyModelPassive(value) { capnp_ts_1.Struct.setUint16(62, value, this); }
    getSafetyParam() { return capnp_ts_1.Struct.getInt16(12, this); }
    setSafetyParam(value) { capnp_ts_1.Struct.setInt16(12, value, this); }
    adoptSteerMaxBP(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(2, this)); }
    disownSteerMaxBP() { return capnp_ts_1.Struct.disown(this.getSteerMaxBP()); }
    getSteerMaxBP() { return capnp_ts_1.Struct.getList(2, capnp.Float32List, this); }
    hasSteerMaxBP() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(2, this)); }
    initSteerMaxBP(length) { return capnp_ts_1.Struct.initList(2, capnp.Float32List, length, this); }
    setSteerMaxBP(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(2, this)); }
    adoptSteerMaxV(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(3, this)); }
    disownSteerMaxV() { return capnp_ts_1.Struct.disown(this.getSteerMaxV()); }
    getSteerMaxV() { return capnp_ts_1.Struct.getList(3, capnp.Float32List, this); }
    hasSteerMaxV() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(3, this)); }
    initSteerMaxV(length) { return capnp_ts_1.Struct.initList(3, capnp.Float32List, length, this); }
    setSteerMaxV(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(3, this)); }
    adoptGasMaxBP(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(4, this)); }
    disownGasMaxBP() { return capnp_ts_1.Struct.disown(this.getGasMaxBP()); }
    getGasMaxBP() { return capnp_ts_1.Struct.getList(4, capnp.Float32List, this); }
    hasGasMaxBP() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(4, this)); }
    initGasMaxBP(length) { return capnp_ts_1.Struct.initList(4, capnp.Float32List, length, this); }
    setGasMaxBP(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(4, this)); }
    adoptGasMaxV(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(5, this)); }
    disownGasMaxV() { return capnp_ts_1.Struct.disown(this.getGasMaxV()); }
    getGasMaxV() { return capnp_ts_1.Struct.getList(5, capnp.Float32List, this); }
    hasGasMaxV() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(5, this)); }
    initGasMaxV(length) { return capnp_ts_1.Struct.initList(5, capnp.Float32List, length, this); }
    setGasMaxV(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(5, this)); }
    adoptBrakeMaxBP(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(6, this)); }
    disownBrakeMaxBP() { return capnp_ts_1.Struct.disown(this.getBrakeMaxBP()); }
    getBrakeMaxBP() { return capnp_ts_1.Struct.getList(6, capnp.Float32List, this); }
    hasBrakeMaxBP() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(6, this)); }
    initBrakeMaxBP(length) { return capnp_ts_1.Struct.initList(6, capnp.Float32List, length, this); }
    setBrakeMaxBP(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(6, this)); }
    adoptBrakeMaxV(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(7, this)); }
    disownBrakeMaxV() { return capnp_ts_1.Struct.disown(this.getBrakeMaxV()); }
    getBrakeMaxV() { return capnp_ts_1.Struct.getList(7, capnp.Float32List, this); }
    hasBrakeMaxV() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(7, this)); }
    initBrakeMaxV(length) { return capnp_ts_1.Struct.initList(7, capnp.Float32List, length, this); }
    setBrakeMaxV(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(7, this)); }
    getMass() { return capnp_ts_1.Struct.getFloat32(16, this); }
    setMass(value) { capnp_ts_1.Struct.setFloat32(16, value, this); }
    getWheelbase() { return capnp_ts_1.Struct.getFloat32(20, this); }
    setWheelbase(value) { capnp_ts_1.Struct.setFloat32(20, value, this); }
    getCenterToFront() { return capnp_ts_1.Struct.getFloat32(24, this); }
    setCenterToFront(value) { capnp_ts_1.Struct.setFloat32(24, value, this); }
    getSteerRatio() { return capnp_ts_1.Struct.getFloat32(28, this); }
    setSteerRatio(value) { capnp_ts_1.Struct.setFloat32(28, value, this); }
    getSteerRatioRear() { return capnp_ts_1.Struct.getFloat32(32, this); }
    setSteerRatioRear(value) { capnp_ts_1.Struct.setFloat32(32, value, this); }
    getRotationalInertia() { return capnp_ts_1.Struct.getFloat32(36, this); }
    setRotationalInertia(value) { capnp_ts_1.Struct.setFloat32(36, value, this); }
    getTireStiffnessFront() { return capnp_ts_1.Struct.getFloat32(40, this); }
    setTireStiffnessFront(value) { capnp_ts_1.Struct.setFloat32(40, value, this); }
    getTireStiffnessRear() { return capnp_ts_1.Struct.getFloat32(44, this); }
    setTireStiffnessRear(value) { capnp_ts_1.Struct.setFloat32(44, value, this); }
    adoptLongitudinalTuning(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(8, this)); }
    disownLongitudinalTuning() { return capnp_ts_1.Struct.disown(this.getLongitudinalTuning()); }
    getLongitudinalTuning() { return capnp_ts_1.Struct.getStruct(8, CarParams_LongitudinalPIDTuning, this); }
    hasLongitudinalTuning() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(8, this)); }
    initLongitudinalTuning() { return capnp_ts_1.Struct.initStructAt(8, CarParams_LongitudinalPIDTuning, this); }
    setLongitudinalTuning(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(8, this)); }
    adoptLateralParams(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(12, this)); }
    disownLateralParams() { return capnp_ts_1.Struct.disown(this.getLateralParams()); }
    getLateralParams() { return capnp_ts_1.Struct.getStruct(12, CarParams_LateralParams, this); }
    hasLateralParams() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(12, this)); }
    initLateralParams() { return capnp_ts_1.Struct.initStructAt(12, CarParams_LateralParams, this); }
    setLateralParams(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(12, this)); }
    getLateralTuning() { return capnp_ts_1.Struct.getAs(CarParams_LateralTuning, this); }
    initLateralTuning() { return capnp_ts_1.Struct.getAs(CarParams_LateralTuning, this); }
    getSteerLimitAlert() { return capnp_ts_1.Struct.getBit(5, this); }
    setSteerLimitAlert(value) { capnp_ts_1.Struct.setBit(5, value, this); }
    getSteerLimitTimer() { return capnp_ts_1.Struct.getFloat32(76, this); }
    setSteerLimitTimer(value) { capnp_ts_1.Struct.setFloat32(76, value, this); }
    getVEgoStopping() { return capnp_ts_1.Struct.getFloat32(48, this); }
    setVEgoStopping(value) { capnp_ts_1.Struct.setFloat32(48, value, this); }
    getDirectAccelControl() { return capnp_ts_1.Struct.getBit(6, this); }
    setDirectAccelControl(value) { capnp_ts_1.Struct.setBit(6, value, this); }
    getStoppingControl() { return capnp_ts_1.Struct.getBit(7, this); }
    setStoppingControl(value) { capnp_ts_1.Struct.setBit(7, value, this); }
    getStartAccel() { return capnp_ts_1.Struct.getFloat32(52, this); }
    setStartAccel(value) { capnp_ts_1.Struct.setFloat32(52, value, this); }
    getSteerRateCost() { return capnp_ts_1.Struct.getFloat32(56, this); }
    setSteerRateCost(value) { capnp_ts_1.Struct.setFloat32(56, value, this); }
    getSteerControlType() { return capnp_ts_1.Struct.getUint16(60, this); }
    setSteerControlType(value) { capnp_ts_1.Struct.setUint16(60, value, this); }
    getRadarOffCan() { return capnp_ts_1.Struct.getBit(8, this); }
    setRadarOffCan(value) { capnp_ts_1.Struct.setBit(8, value, this); }
    getMinSpeedCan() { return capnp_ts_1.Struct.getFloat32(84, this); }
    setMinSpeedCan(value) { capnp_ts_1.Struct.setFloat32(84, value, this); }
    getStoppingBrakeRate() { return capnp_ts_1.Struct.getFloat32(88, this); }
    setStoppingBrakeRate(value) { capnp_ts_1.Struct.setFloat32(88, value, this); }
    getStartingBrakeRate() { return capnp_ts_1.Struct.getFloat32(92, this); }
    setStartingBrakeRate(value) { capnp_ts_1.Struct.setFloat32(92, value, this); }
    getSteerActuatorDelay() { return capnp_ts_1.Struct.getFloat32(64, this); }
    setSteerActuatorDelay(value) { capnp_ts_1.Struct.setFloat32(64, value, this); }
    getOpenpilotLongitudinalControl() { return capnp_ts_1.Struct.getBit(9, this); }
    setOpenpilotLongitudinalControl(value) { capnp_ts_1.Struct.setBit(9, value, this); }
    getCarVin() { return capnp_ts_1.Struct.getText(10, this); }
    setCarVin(value) { capnp_ts_1.Struct.setText(10, value, this); }
    getDashcamOnly() { return capnp_ts_1.Struct.getBit(11, this); }
    setDashcamOnly(value) { capnp_ts_1.Struct.setBit(11, value, this); }
    getTransmissionType() { return capnp_ts_1.Struct.getUint16(68, this); }
    setTransmissionType(value) { capnp_ts_1.Struct.setUint16(68, value, this); }
    adoptCarFw(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(11, this)); }
    disownCarFw() { return capnp_ts_1.Struct.disown(this.getCarFw()); }
    getCarFw() { return capnp_ts_1.Struct.getList(11, CarParams._CarFw, this); }
    hasCarFw() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(11, this)); }
    initCarFw(length) { return capnp_ts_1.Struct.initList(11, CarParams._CarFw, length, this); }
    setCarFw(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(11, this)); }
    getRadarTimeStep() { return capnp_ts_1.Struct.getFloat32(72, this, CarParams._capnp.defaultRadarTimeStep); }
    setRadarTimeStep(value) { capnp_ts_1.Struct.setFloat32(72, value, this); }
    getCommunityFeature() { return capnp_ts_1.Struct.getBit(12, this); }
    setCommunityFeature(value) { capnp_ts_1.Struct.setBit(12, value, this); }
    getFingerprintSource() { return capnp_ts_1.Struct.getUint16(70, this); }
    setFingerprintSource(value) { capnp_ts_1.Struct.setUint16(70, value, this); }
    getNetworkLocation() { return capnp_ts_1.Struct.getUint16(80, this); }
    setNetworkLocation(value) { capnp_ts_1.Struct.setUint16(80, value, this); }
    getIsPandaBlackDEPRECATED() { return capnp_ts_1.Struct.getBit(10, this); }
    setIsPandaBlackDEPRECATED(value) { capnp_ts_1.Struct.setBit(10, value, this); }
    toString() { return "CarParams_" + super.toString(); }
}
CarParams.LateralParams = CarParams_LateralParams;
CarParams.LateralPIDTuning = CarParams_LateralPIDTuning;
CarParams.LongitudinalPIDTuning = CarParams_LongitudinalPIDTuning;
CarParams.LateralINDITuning = CarParams_LateralINDITuning;
CarParams.LateralLQRTuning = CarParams_LateralLQRTuning;
CarParams.SafetyModel = CarParams_SafetyModel;
CarParams.SteerControlType = CarParams_SteerControlType;
CarParams.TransmissionType = CarParams_TransmissionType;
CarParams.CarFw = CarParams_CarFw;
CarParams.Ecu = CarParams_Ecu;
CarParams.FingerprintSource = CarParams_FingerprintSource;
CarParams.NetworkLocation = CarParams_NetworkLocation;
CarParams._capnp = { displayName: "CarParams", id: "8c69372490aaa9da", size: new capnp_ts_1.ObjectSize(104, 13), defaultSafetyModelPassive: capnp.getUint16Mask(0), defaultRadarTimeStep: capnp.getFloat32Mask(0.05000000074505806) };
exports.CarParams = CarParams;
CarState._Events = capnp.CompositeList(CarEvent);
CarState._ButtonEvents = capnp.CompositeList(CarState_ButtonEvent);
RadarData._Points = capnp.CompositeList(RadarData_RadarPoint);
CarParams._CarFw = capnp.CompositeList(CarParams_CarFw);
